name: openchat_frontend
description: Frontend for the MOSS chatbot
publish_to: 'none'
version: 1.2.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  
  flutter_markdown:
    git:
      url: https://github.com/singularity-s0/flutter_markdown_selectable.git
  flutter_native_splash: ^2.2.17
  provider: ^6.0.5
  clipboard: ^0.1.3
  dio: ^4.0.6
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.17
  local_hero: ^0.2.0
  image_downloader_web: ^2.0.2
  web_socket_channel: ^2.3.0
  http: ^0.13.5

  # Chat UI dependencies
  diffutil_dart: ^3.0.0
  flutter_chat_types: ^3.6.0
  scroll_to_index: ^3.0.1
  visibility_detector: ^0.3.3
  flutter_link_previewer: ^3.2.0
  url_launcher: ^6.1.9
  flutter_parsed_text: ^2.2.1
  highlighter: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
#   flutter_launcher_icons: ^0.11.0

# dependency_overrides:
#   image: ^3.0.0 # Needed for flutter_launcher_icons

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    # - family: NotoSerif
    #   fonts:
    #     - asset: assets/fonts/H4chBXePl9DZ0Xe7gG9cyOj7oqCcbzhqDtg.otf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/eJ4cxQe85Lo39t-LVoKa26CWcynf_cDxXwCLxiixG1c.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/W5F8_SL0XFawnjxHGsZjJA.ttf

flutter_native_splash:
  color: "#FDFBFF"
  color_dark: "#1B1B1F"
  image: assets/images/logo.png

flutter_icons:
  android: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#ffffffff"
    theme_color: "#ffffffff"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"