name: openchat_frontend
description: Frontend for the MOSS chatbot
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_chat_ui: ^1.6.6
  flutter_markdown: ^0.6.13+1
  flutter_native_splash: ^2.2.17
  provider: ^6.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  branding: assets/images/logo.png