name: openchat_frontend
description: Frontend for the MOSS chatbot
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  
  flutter_markdown: ^0.6.13+1
  flutter_native_splash: ^2.2.17
  provider: ^6.0.5
  flutter_highlighter: ^0.1.1
  clipboard: ^0.1.3

  # Chat UI dependencies
  diffutil_dart: ^3.0.0
  flutter_chat_types: ^3.6.0
  scroll_to_index: ^3.0.1
  visibility_detector: ^0.3.3
  flutter_link_previewer: ^3.2.0
  url_launcher: ^6.1.9
  flutter_parsed_text: ^2.2.1
  dio: ^4.0.6
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_native_splash:
  color: "#FDFBFF"
  color_dark: "#1B1B1F"
  image: assets/images/logo.png